# Generated by Django 4.2.5 on 2023-11-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_alter_group_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', to='basic_app.userprofileinfo'),
        ),
    ]
