# Generated by Django 4.2.5 on 2023-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_postgroup_imagegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgroup',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
