# Generated by Django 4.2.5 on 2023-11-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_alter_postgroup_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.userprofileinfo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.postgroup')),
            ],
        ),
    ]
