# Generated by Django 4.2.5 on 2023-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ad_group',
            field=models.ManyToManyField(blank=True, to='basic_app.userprofileinfo'),
        ),
    ]
