# Generated by Django 4.2.5 on 2023-11-24 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_group_ad_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_page', to='basic_app.userprofileinfo')),
                ('follow', models.ManyToManyField(related_name='joined_page', to='basic_app.userprofileinfo')),
            ],
        ),
    ]
