# Generated by Django 4.2.5 on 2023-11-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ad_page',
            field=models.ManyToManyField(blank=True, to='basic_app.userprofileinfo'),
        ),
    ]
